// scripts/extract-palette.mjs
//
// Reads the first image in /public (or /public/img) matching jpg|jpeg|png|webp,
// extracts a 6-swatch palette via node-vibrant, and writes:
//   - app/palette.css       (CSS variables consumed by globals.css)
//   - lib/palette.json      (typed at runtime via lib/palette.ts)
// Runs as `prebuild` and `predev`.

import { existsSync, readdirSync, statSync, mkdirSync, writeFileSync } from "node:fs";
import { join, posix } from "node:path";

const ROOT = process.cwd();
const PUBLIC_DIR = join(ROOT, "public");
const APP_DIR = join(ROOT, "app");
const LIB_DIR = join(ROOT, "lib");

const IMG_RE = /\.(jpe?g|png|webp)$/i;

function findImage(dir) {
  if (!existsSync(dir)) return null;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const s = statSync(full);
    if (s.isDirectory()) {
      const nested = findImage(full);
      if (nested) return nested;
    } else if (IMG_RE.test(entry)) {
      return full;
    }
  }
  return null;
}

function toPublicUrl(absPath) {
  const rel = absPath.slice(PUBLIC_DIR.length).split(/[\\/]/g).filter(Boolean);
  return "/" + rel.map(encodeURIComponent).join(posix.sep);
}

function rgbToHex({ rgb }) {
  const [r, g, b] = rgb.map((n) => Math.max(0, Math.min(255, Math.round(n))));
  return "#" + [r, g, b].map((n) => n.toString(16).padStart(2, "0")).join("");
}

const FALLBACK = {
  Vibrant: "#6366f1",
  LightVibrant: "#a5b4fc",
  DarkVibrant: "#312e81",
  Muted: "#475569",
  LightMuted: "#cbd5e1",
  DarkMuted: "#1e293b",
};

async function main() {
  const found = findImage(PUBLIC_DIR);
  let palette = { ...FALLBACK };
  let imageUrl = null;

  if (found) {
    imageUrl = toPublicUrl(found);
    try {
      const { Vibrant } = await import("node-vibrant/node");
      const result = await Vibrant.from(found).getPalette();
      for (const k of Object.keys(FALLBACK)) {
        const swatch = result[k];
        if (swatch) palette[k] = rgbToHex(swatch);
      }
      console.log(`[palette] extracted from ${imageUrl}`);
    } catch (err) {
      console.warn("[palette] extraction failed, using fallback:", err?.message ?? err);
    }
  } else {
    console.warn("[palette] no image found in /public; using fallback palette");
  }

  // ----- write CSS variables -----
  const css = `/* AUTO-GENERATED by scripts/extract-palette.mjs — do not edit by hand */
:root {
  --palette-vibrant: ${palette.Vibrant};
  --palette-light-vibrant: ${palette.LightVibrant};
  --palette-dark-vibrant: ${palette.DarkVibrant};
  --palette-muted: ${palette.Muted};
  --palette-light-muted: ${palette.LightMuted};
  --palette-dark-muted: ${palette.DarkMuted};
}
`;
  if (!existsSync(APP_DIR)) mkdirSync(APP_DIR, { recursive: true });
  writeFileSync(join(APP_DIR, "palette.css"), css, "utf8");

  // ----- write JSON consumed by lib/palette.ts -----
  if (!existsSync(LIB_DIR)) mkdirSync(LIB_DIR, { recursive: true });
  writeFileSync(
    join(LIB_DIR, "palette.json"),
    JSON.stringify({ image: imageUrl, ...palette }, null, 2) + "\n",
    "utf8",
  );

  console.log("[palette] wrote app/palette.css and lib/palette.json");
}

main().catch((err) => {
  console.error("[palette] fatal:", err);
  process.exit(0); // never block the build
});
